### ISSUE TITLE
Limiting Active Users - selenium tests

### ISSUE THREAD

**Issue by wendyinnis** [LabKey/testAutomation#1124]
#### Rationale
We want the option for LabKey Server deployments to limit the number of active users. See the spec for details: https://docs.google.com/document/d/15TenwfucW9XNO8OhHB6ibEIIyxPycbB9SqcXtoimcgE/edit#

This story adds automation for this new feature.

#### Related Pull Requests
- https://github.com/LabKey/platform/pull/3334

**Tasks**

- [x] Add tasks (0.25) @labkey-sweta
- [x] Create LimitActiveUserPage (3) @labkey-sweta
- [x] ActiveUserLimitationTest.testUserWarning - 3 @labkey-sweta
- [x] ActiveUserLimitationTest.testUserLimits - 3 @labkey-sweta
- [x] ActiveUserLimitationTest.testSystemUserLimitation - 3 @labkey-sweta
- [x] ActiveUserLimitationTest.testActivateAndDeactivateUserWithLimits - 3 @labkey-sweta
- [x] Add test case in LDAPTest -3 @labkey-sweta
- [x] Code review changes - 3 @labkey-sweta 
- [x] code review -2 @labkey-adam 
- [ ] merge - 1 @labkey-sweta
**Total Hours -21.25hrs-
