### ISSUE TITLE
[LK SDMS] SQL Server Phase Out: TeamCity Windows Testing - planning

### ISSUE THREAD

**Issue by labkey-danield** [LabKey/testAutomation#2163]
[Spec](https://docs.google.com/document/d/1tAcrTzEoDhm5-HVkX_MRjtr2LwOKdq7zS_ovJl8kmbM/edit?usp=sharing)
[Github epic](https://github.com/LabKey/testAutomation/issues/2170)

We need to add more frequent windows coverage to our test automation. Currently test automation is only run on MSSQL for the ESR releases. This does identify issues but they are frequently late. We should be running against windows more frequently.

### Tasks 📍 
- [x] Write Background, Goals @labkey-chrisj 
- [x] Break up epic into actionable stories
- [x] Data gathering 
- [x] Write Implementation Plan @labkey-chrisj  
  - [x] Review @labkey-klum 
  - [x] Review @labkey-nicka 
  - [x] Review @labkey-jeckels 
  - [x] Review @labkey-jony 
- [x] Update spec @labkey-chrisj  
- [x] Spec review - @labkey-danield 
- [x] Incorporate Feedback 
- [x] Evaluate results from 24.12 runs on windows 2

**Comment by labkey-jeckels** [comment]
@labkey-chrisj I read through the spec and from my review it's covering the important things.

There are a number of open questions or possible approaches and it's not clear to me which ones you truly need input to make a decision. I think that for many of them you have a good idea of a reasonable approach but are still open to alternatives.

Can you run through the doc, and handle them by either:
1. Proposing an approach when you're in a reasonable position already.
2. Note cases where you plan to make a call during the implementation phase (hopefully not too many, but fine to have some).
3. Tagging people when you want their input.
