### ISSUE TITLE
Test Automation for LabKey Server Upgrade - planning

### ISSUE THREAD

**Issue by labkey-danield** [LabKey/testAutomation#2164]
[Epic](https://github.com/LabKey/testAutomation/issues/2178)
[Spec](https://docs.google.com/document/d/19TxnlcC1IRiS5yYRYCRg4ncmWNXEtgFZ8TnbY3kk7FE/edit?usp=sharing)

Add test automation that validates the LKS upgrade scenario.

### Tasks 📍  
- [x] Start Spec - 0.5hr @labkey-danield 
- [x] Exploration - 2hr @labkey-danield
- [x] Testing Approach - 0.5 @labkey-danield   
- [x] Discussion @labkey-stuartm
- [x] Update with discussion feedback - 1hr @labkey-danield 
- [x] Review
    - [x]  @labkey-jeckels 
    - [x] @labkey-adam 
    - [x] @labkey-klum 
- [x] Open Questions/Design decisions updated in spec - 1.0hr @labkey-danield 
- [x] Review \ Sign Off - .5hr
