### ISSUE TITLE
[SDMS] SQL Server Phase Out: TeamCity Windows Testing: Define and implement pg-on-windows suite

### ISSUE THREAD

**Issue by labkey-elielz** [LabKey/testAutomation#2183]
[Spec](https://docs.google.com/document/d/1tAcrTzEoDhm5-HVkX_MRjtr2LwOKdq7zS_ovJl8kmbM/edit?usp=sharing)
[Github epic](https://github.com/LabKey/testAutomation/issues/2170)

[Related Story](https://github.com/orgs/LabKey/projects/5/views/2?filterQuery=windows&pane=issue&itemId=87149428&issue=LabKey%7Ckanban%7C355)

### Tasks 📌 
- [x] Define Test Suite Requirements
- [x] Configure Test Suite for Windows Environment
- [x] Run Initial Suite and Gather Data
- [x] Consider Client & AMI Compatibility
- [x] Stabilize and Optimize for Regular Runs
- [x] Update the Biologics-Windows config to run weekly (Friday Afternoon)
  - [ ] Test issues
