### ISSUE TITLE
[SDMS] SQL Server Phase Out: TeamCity Windows Testing: Run Kitchen Sink Suite

### ISSUE THREAD

**Issue by labkey-elielz** [LabKey/testAutomation#2184]
[Spec](https://docs.google.com/document/d/1tAcrTzEoDhm5-HVkX_MRjtr2LwOKdq7zS_ovJl8kmbM/edit?usp=sharing)
[Github epic](https://github.com/LabKey/testAutomation/issues/2170)

[Related Story](https://github.com/orgs/LabKey/projects/5/views/2?filterQuery=windows&pane=issue&itemId=87149428&issue=LabKey%7Ckanban%7C355)

### Tasks 📌 
- [ ] Execute the large test suite on both Windows and Linux environments
- [ ] Document and categorize failures into "test noise" vs. "product noise."
- [ ] Make Decisions on Noisy Tests
- [ ] Define and implement fast-running pg-on-windows suite
  - [ ] (add sub-tasks)
- [x]  Start list for small/fast test
  - [ ] Finalize list 
- [ ] Identify the subset of tests that can be included in the fast-running PostgreSQL-on-Windows suite.
- [ ] (add tasks)
