### ISSUE TITLE
[SDMS] SQL Server Phase Out: TeamCity Windows Testing: Biologics on Win-PG

### ISSUE THREAD

**Issue by labkey-chrisj** [LabKey/testAutomation#2195]
[Spec](https://docs.google.com/document/d/1tAcrTzEoDhm5-HVkX_MRjtr2LwOKdq7zS_ovJl8kmbM/edit?usp=sharing)
[Github epic](https://github.com/LabKey/testAutomation/issues/2170)

## Tasks 📍 

- [x] Search existing bugs for 'windows' to find test candidates 2
- [x] Search test codebase for candidates 2
- [x] Sync @labkey-tchad 
- [x] Configure suite 2
- [x] Create suite file and PR
- [x] copy configs and edit to run with windows agent
- [x] remove/disable vcs trigger
- [x] initial run, analyze results
- [x] code review @labkey-danield 
- [x] pr & merge
- [x] config review @labkey-tchad 
- [x] Review feedback

**Comment by labkey-chrisj** [comment]
Biologics PG config review. Looks pretty good, just a few things to tidy up:
 - The composite build shouldn't have more VCS roots than the build(s) it depends on. Remove extra VCS templates then detach VCS roots: https://teamcity.labkey.org/admin/editBuildTypeVcsRoots.html?init=1&id=buildType:LabKey_Trunk_Premium_ProductSuites_Biologics_BiologicsPostgresWindows The same probably goes for whatever build you copied from
 - Should remove puppeteer VCS root, properties, and build steps (I'm assuming the docker container doesn't work on Windows since you disabled the build steps)
 - Have just the composite build report GitHub build status (Remove "GitHub Commit Status" template)

One TeamCity "quirk" to be aware of: detaching a template leaves everything from that template. Afterward you have to go through and manually delete any VCS roots, build steps, properties, etc.

(JetBrains is aware of the "quirk": https://youtrack.jetbrains.com/issue/TW-50625/Allow-user-to-choose-if-she-wants-to-copy-the-template-settings-to-a-config-while-detaching-it-from-templates-or-not)
